version: "3.8"

networks:
  main:

services:
  app:
    image: ${DOCKER_USERNAME}/csharptwit-${STAGE}
    networks:
      - main
    ports:
      - target: 8080
        published: 5000
    environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

  # docker stack deploy --compose-file compose.yml stackdemo