version: '3'

services:
  minitwit:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__DefaultConnection=Data Source=./app/minitwit.db # connection string to use SQLite database

    build:
      context: .
      dockerfile: ./csharp-minitwit/Dockerfile
    ports:
      - "8080:8080"