auth_enabled: false                                  
                                                     
server:                                              
  http_listen_port: 3100                             
                                                     
ingester:                                            
  lifecycler:                                        
    address: 127.0.0.1                               
    ring:                                            
      kvstore:                                       
        store: inmemory                              
      replication_factor: 1                          
  chunk_idle_period: 3m                              
  chunk_retain_period: 1m                            
                                                     
schema_config:                                       
  configs:                                           
    - from: 2020-10-24                               
      store: boltdb-shipper                          
      object_store: filesystem                       
      schema: v11                                    
      index:                                         
        prefix: index_                               
        period: 24h                                  
                                                     
storage_config:                                      
  boltdb_shipper:                                    
    active_index_directory: /opt/loki/index          
    cache_location: /opt/loki/index_cache            
    shared_store: filesystem                         
  filesystem:                                        
    directory: /opt/loki/chunks                      
                                                     
compactor:                                           
  working_directory: /opt/loki/compactor             
  shared_store: filesystem                           
                                                     
limits_config:                                       
  enforce_metric_name: false                         
  reject_old_samples: true                           
  reject_old_samples_max_age: 168h        