version: "3.8"

networks:
  main:

services:
  minitwitimage:
    image: ${DOCKER_USERNAME}/csharptwitimage
    container_name: csharp-minitwit
    networks:
      - main
    ports:
      - "5000:8080"
    volumes:
      - /mnt/database:/app/Databases/volume