name: Format check on push
on:
  push:
    branches:
      - feature/software-quality-tools
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Change to the directory where your solution is located
      - name: Change to project directory
        run: cd ./csharp-minitwit/

      - name: Restore dependencies
        run: dotnet restore csharp-minitwit.sln

      - name: Format
        run: dotnet format csharp-minitwit.sln --verify-no-changes --verbosity diagnostic
