# Release action with semantic release
name: Release

on:
  ## Only manually release for now
 ## workflow_dispatch:
  push:
    branches:
      ##- main
      - feature/68-automatic-release-workflow


jobs:
  release:
    name: Release to NPM
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Setup .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Run npm install
        run: npm install
      - name: Semantic Release
        run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
