name: Run Tests
# on:
#   workflow_run:
#     workflows: ["Format Check"]
#     types:
#       - completed
on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review] 

jobs:
  build-image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Build Docker image
          run: docker build -t csharp-minitwit:latest ./csharp-minitwit

        - name: Wait 5 seconds
          run: sleep 5

  run-tests:
    needs: build-image
    runs-on: ubuntu-latest
    services:
      csharp-minitwit:
        image: csharp-minitwit:latest
        ports:
          - 5000:5000
        options: --detach
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check Public Endpoint
        run: |
          response=$(curl -v http://localhost:5000/public)
          echo "Response: $response"

      - name: Print Docker Logs
        if: ${{ failure() }}
        run: docker logs csharp-minitwit-container

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          cd ./csharp-minitwit/Tests
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        run: |
          cd ./csharp-minitwit/Tests
          pytest minitwit_sim_api_test.py
          pytest refactored_minitwit_tests.py

      - name: Clean up
        run: |
          docker stop csharp-minitwit-container
          docker rm csharp-minitwit-container
