name: Run Tests
# on:
#   workflow_run:
#     workflows: ["Format Check"]
#     types:
#       - completed
on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review] 

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Wait for docker
        run:
            sleep 5

      - name: Build Docker image
        run: docker build -t csharp-minitwit:latest ./csharp-minitwit

      - name: Run Docker container
        run: |
          docker run -d --name csharp-minitwit-container -p 5000:5000 csharp-minitwit:latest

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Wait for the service to be up
        run:
            sleep 10

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r ./Tests/requirements.txt

      - name: Run Python tests
        run: |
          pytest Tests/minitwit_sim_api_test.py
          pytest Tests/refactored_minitwit_tests.py

      - name: Clean up
        run: |
          docker stop csharp-minitwit-container
          docker rm csharp-minitwit-container
