name: Run Tests
on:
  workflow_run:
    workflows: ["Format Check"]
    types:
      - completed

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      app:
        image: csharp-minitwit:latest
        options: --health-cmd='curl -f http://localhost:5000/public || exit 1' --health-interval=10s --health-retries=3 --health-start-period=30s --health-timeout=10s
        ports:
          - 5000:5000
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t csharp-minitwit:latest ./csharp-minitwit

      - name: Wait for the service to be healthy
        run: |
          until [ "$(docker inspect --format='{{.State.Health.Status}}' app)" == "healthy" ]; do
            echo "Waiting for Docker service to be healthy..."
            sleep 5
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python tests
        env:
          BASE_URL: http://localhost:5000
        run: |
          cd ./Tests
          pytest minitwit_sim_api_test.py
          pytest refactored_minitwit_tests.py
